name: Update BigCommerce on Push to Master

on:
  push:
    branches:
      - master

jobs:
  update-bigcommerce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19' # or any version that is compatible with your project

      - name: Install stencil CLI
        run: npm install -g @bigcommerce/stencil-cli

      - name: Install dependencies
        run: npm install

      - name: Authenticate with BigCommerce
        run: stencil init --url https://dev-q2.mybigcommerce.com --token ${{ secrets.BIGCOMMERCE_API_TOKEN }}

      - name: Build theme
        run: stencil bundle

      - name: Push changes to BigCommerce
        run: stencil push
