name: Update BigCommerce on Push to Master

on:
  push:
    branches:
      - master

jobs:
  update-bigcommerce:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stencil CLI
        run: npm install -g @bigcommerce/stencil-cli

      - name: Authenticate with BigCommerce
        run: stencil init --url ${{ secrets.BIGCOMMERCE_STORE_URL }} --token ${{ secrets.BIGCOMMERCE_API_TOKEN }}

      - name: Build theme
        run: stencil bundle

      - name: Push changes to BigCommerce
        run: stencil push
